### ISSUE TITLE
Remove all comments in `index.d.ts` for releases to improve `tsc` performance

### ISSUE THREAD

**Issue by LukasKalbertodt** [frenic/csstype#103]
I just created a new TS React project. I have `@types/react` as one of my dependency, which in turn requires `csstype`. I noticed that `tsc` is fairly slow, even with `--skipLibCheck`. `--diagnostics` then showed that of the roughly 0.92s total time, 0.54s were spent parsing. Since my new project only has a few lines of code, this is about parsing code of dependencies. 

After some more searching and trying stuff, I found that `csstype/index.d.ts` is the largest file opened by `tsc`. Here are the top largest `.d.ts` files:

```
1,6M    node_modules/csstype/index.d.ts
816K    node_modules/typescript/lib/lib.dom.d.ts
208K    node_modules/typescript/lib/lib.es5.d.ts
136K    node_modules/@types/react/index.d.ts
120K    node_modules/@types/node/inspector.d.ts
112K    node_modules/@types/node/fs.d.ts
```

Opening `csstype/index.d.ts` revealed that a very large part of that file was comments. Removing those comments pretty consistently brings down the parse time to roughly 0.47s. 

I know we are "only" talking about 70ms, but considering that all TS React projects pay that on every type check, I think it's worth taking those savings. The question now is: do the comments in the `index.d.ts` file uploaded to the NPM registry serve any purpose? Do people actually open that file and read the comments? I would rather expect they read those comments/documentation somewhere else. In that case, removing the comments from release would not hurt, right?

Curious about what you think :) 
(I am pretty new in the whole TS and JS ecosystem, so please excuse if my idea doesn't make sense)

**Comment by meyer** [comment]
@LukasKalbertodt welcome to the world of TypeScript! Hope you’re having a good time so far.

Those comments are actually quite helpful for end users. Docstring comments (comments that start with `/**`) appear inline wherever the typed attributes appear. For example, this is what I see in VS Code as I type new CSS properties:

![screenshot](https://user-images.githubusercontent.com/13781/87095160-17e12200-c1f5-11ea-829e-a3fb5b5c5af5.png)

Additionally, that ~70ms parse penalty is only paid when types are _imported_ or when they _change_. Most decent editors these days run a [language server](https://microsoft.github.io/language-server-protocol/) that caches build metadata (including types) so that rebuilds can occur [incrementally](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#faster-subsequent-builds-with-the---incremental-flag).

**Comment by LukasKalbertodt** [comment]
> Hope you’re having a good time so far.

Your pleasant comment certainly helped with me having a good time!

> Those comments are actually quite helpful for end users. [...]

Interesting! I wouldn't have thought so, but I guess it kind of makes sense.

> Additionally, that ~70ms parse penalty is only paid when types are imported or when they change.

In my case, tsc always reads and parses all of those files on each invocation. I also already saw and tried the `--incremental` flag, but it doesn't seem to help with parse times. I think this option is only useful for actual codegen. 

But oh well, I guess removing useful comments from libraries is certainly not the way to improve that "`tsc` in terminal" speed. I'ma close this issue. Thanks again!
