### ISSUE TITLE
Interface vs intersection types w/ Flow

### ISSUE THREAD

**Issue by rtsao** [frenic/csstype#11]
It'd be nice to allow for some customization of properties. A use case would be custom `fontFace` or `animationName` property name values for declarative `@keyframes` or `@font-face` rules.

For example:
```js
const animation = {
  from: {color: "red"},
  to: {color: "blue"}
};

const style = {
  animationName: animation
};
```

Unfortunately, [types can't be easily extended in Flow](https://github.com/facebook/flow/issues/396).

So when using Flow, there's two possible options:

1. Make add parameterized types for `animationName` and `fontFace` values.
2. Use Flow utility types as a means of composition and override mechanism.

Option 1 seems a bit clunky, because the parameterization is overly specific to a particular implementation/use case that may not be generically applicable. Adding generics for all the things is probably not sustainable, as folks may want to add more and more things.

Option 2 seems much more sustainable, as this customization can simply happen outside of this library. However, this doesn't work well with interface types and Flow.

[Here's a simple reproduction case in the Flow playground](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDekBA-AFygB2ArgLYBGWATgL4Dcy62oAEIBDdsTItRNUAGcU7AJZ0A5j2TAAVBsSgNoAKoyly0EpQdIwgMZYZoABQsGcrABMAlDo3BEZi9ZxBWBQACwBGUCwAD3M6Vzt8WAAaIVEyNX4cAHUFUNgGFBF2CJIAEgARBUhIAB4g0LCU0kl2WmE6NE4APl4rWDo5UGEw2hy8gqKSsgpYWgAiGRD86FdI9nZYMUcC0FdYW3pggEJ3ObU-dksbUAB5ADcORVcsCOjY+NAxpYnRCNIdUAtaSMVgcRBqPoDFCAka3B7rBTPKbkAjzRbLVaPTYOJzQvYHOjHU5qRCabS6AxGFSmOjmdgyLBWFAKfqgTJ2ezwTYAaxknl0PkyQmCIQATOJEqAAGSpdi8IVffKFUTisqVap1EWipotNodbq8ECgSGDYSi0a5b7K9iq6ao0ALb4rNYbdhneWYHD3R6IrC2xU-YrSsgAoG0EFsdjgw1gE3QljmuE+5625qiNFOzHrTbuxBAA).

Other than keeping the code generation the same between Flow and Typescript, was there any other reason to use interface types in the Flow case?

I propose changing the Flow generation code in this library to use object intersection types instead of `interface`s and `extends`, which I think will make customization/composition much easier. I'm temporarily using a forked version of this library in Styletron to get around this, but this change should solve the problem. Happy to put up a PR for this, just figured I'd make an issue first.

Thanks for making a such an awesome library 😄

**Comment by frenic** [comment]
The main reason it's interfaces is because it was inherited by the TypeScript definition. In TypeScript the preview when you hovered it in VS Code using TypeScript displays less details when you hover it.

Interface
![capture](https://user-images.githubusercontent.com/237182/36890201-588985ca-1dfd-11e8-9bfb-789db90c8706.PNG)

Type Alias
![capture2](https://user-images.githubusercontent.com/237182/36890176-4752b966-1dfd-11e8-955a-5f2fd811f5ba.PNG)

This becomes even worse when you combine it with other types. Is it the same with Flow?

There's no technical advantage of using interfaces in this case other than that what I can think of in TypeScript. I'm open to convert interfaces intersection types in the Flow definition if it provides more flexibility.
