### ISSUE TITLE
Bundlephobia doesn't work - What's the size of this package?

### ISSUE THREAD

**Issue by Vadorequest** [frenic/csstype#112]
https://bundlephobia.com/result?p=csstype fails for this package but works for thousands of others, any idea why?

My goal was to check how much this package weights in the browser before considering adding it.

**Comment by gregveres** [comment]
someone more knowledgeable than I can chime in, but I am 99% certain there is no run-time hit for the package. I use it for typescript and my node_modules directory only has index.d.ts, which means it is only a set of type declarations to make working with css easier. 

I did go check out the issue on next-right-now. The advantage of using csstype is that you get tooling support because of the type declarations. You get variable name completion, which makes things much easier than the type declaration you seem to be using.

**Comment by Vadorequest** [comment]
Thank you for confirming its size and usefulness :)
