### ISSUE TITLE
Compatibility with Typescript 4.1

### ISSUE THREAD

**Issue by phiresky** [frenic/csstype#118]
[TS 4.1](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/)

adds string literal type concatenation which should make this module work a lot better.

But also, it seems to make `(string & {} )` be never, so all the current types break. 

For example, `color: "#00d54f"` is an error:

```
Type '"#00d54f"' is not assignable to type '"inherit" | "-moz-initial" ...
```

**Comment by frenic** [comment]
I've added tests against Typescript 4.1-beta for a while ago and didn't see any problems. I just upgraded to 4.1.2 and added [a `color` property](https://github.com/frenic/csstype/blob/4f2456d3199b480da8fff805be9ffd480fff10f5/__tests__/__fixtures__/typecheck.ts#L15) but there's no error on that 🤔

**Comment by frenic** [comment]
String template literal will be used somehow. I'll ensure you that. But I see that as a major change so it will be on hold for a while until 4.1 is more established. It would cause chaos otherwise.

But I need more information regarding your other issue. Can you create a repository where you can reproduce the error?

**Comment by phiresky** [comment]
sorry, turns out it wasn't the fault of this library. The problem was I have this in my code base somewhere:

```ts
declare global {
	interface Number {
		"~type": "number";
	}
	interface String {
		"~type": "string";
	}
}
```

This worked fine in the older versions, but in TS 4.1 apparently this means that all string & .... merges break.
