### ISSUE TITLE
string "none" not assignable to text-transform or user-select

### ISSUE THREAD

**Issue by SamHH** [frenic/csstype#38]
As far as I can tell, React's TypeScript types via DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/react) recently began using this library for CSS types / stopped allowing a string fallback. Since updating my `@types/react` dependency, I've been getting the following errors for this (example) piece of code:

```javascript
<span
  style={{
    userSelect: 'none',
    textTransform: 'none',
  }}
/>
```

`Type '<style object>' is not assigning to type 'CSSProperties'. Types of property '[userSelect / textTransform]' are incompatible. Type 'string' is not assignable to type '[UserSelectProperty / TextTransformProperty]'.`

Sorry if this repo isn't the right place to bring this up, it's hard to tell. Cheers!

**Comment by pelotom** [comment]
@SamHH 

> ```ts
> <span
>   style={{
>     userSelect: 'none',
>     textTransform: 'none',
>   }}
> />
> ```

That code works fine for me. Are you sure you didn't actually do something like this?

```ts
const style = {
  userSelect: 'none',
  textTransform: 'none',
};

<span style={style} />
```

This fails with the errors you gave because of [type widening](https://blog.mariusschulz.com/2017/02/04/typescript-2-1-literal-type-widening); the literal `'none'` is being inferred as the widened type `string`. You can fix it by inlining the style or by using a type annotation, e.g.

```ts
const style: React.CSSProperties = {
  userSelect: 'none',
  textTransform: 'none',
};
```

**Comment by SamHH** [comment]
That is indeed what it was! Thanks a lot, I had no idea about type widening, but that makes perfect sense in retrospect.
