### ISSUE TITLE
why need `| string` in the properties like `display`

### ISSUE THREAD

**Issue by xwchris** [frenic/csstype#80]
In the source code, I found the property `display`'s type like this
```js
type DisplayProperty = Globals | DisplayOutside | DisplayInside | DisplayInternal | DisplayLegacy | "contents" | "list-item" | "none" | string;
```

the result of `DisplayProperty` is `string` because of the `| string`.  As a result of this, I can't have a autocompletion in ts.

So why need `| string` in the properties like `display`?

**Comment by frenic** [comment]
As mentioned here https://github.com/frenic/csstype/issues/8#issuecomment-364845647 the syntax for `display` tells us that you're able to use space separated values. That's why union string is needed. But the autocomplete however seems to be solved in #74. So it will hopefully work in v3 that will be released soon.
