### ISSUE TITLE
Document Formal Syntax as part of jsdoc for each of the properties.

### ISSUE THREAD

**Issue by nojvek** [frenic/csstype#86]
I have to say, I really really love this module. I was going to spend a significant amount of time crawling mdn and generating types but found exactly what I wanted. 

![image](https://user-images.githubusercontent.com/1018196/77235490-4b7b3c00-6b73-11ea-9138-f432b7141273.png)

For composite properties e.g padding, overlow, display, height e.t.c, MDN displays a fantastic formal-syntax. 

Now I fully agree that typescript isn't able to represent all of it and `csstype` has done a tremendous job of properties that have enumerated strings e.g `cursor: 'pointer'` e.t.c

But having the formal syntax in code completion documentation panel is very helpful. It's usually a very small concise string so doesn't add a lot of weight.

![image](https://user-images.githubusercontent.com/1018196/77235560-fee43080-6b73-11ea-8af8-29c11eaa8180.png)

![image](https://user-images.githubusercontent.com/1018196/77794695-8a086f00-7029-11ea-97f0-0e7fe961d12f.png)

I'm gonna try making a PR, if people aren't against it.

**Comment by frenic** [comment]
I'm not sure people will read the formal syntax as a way to understand it. Because...

 1. They usually contain data types which isn't displayed anywhere, like `<box>`
 1. They are sometimes quite complex, like `[ <length> | <percentage> ] && [ border-box | content-box ]? | available | min-content | max-content | fit-content | auto`
 1. Some of them are really long, like `[ [ <url> [ <x> <y> ]? , ]* [ auto | default | none | context-menu | help | pointer | progress | wait | cell | crosshair | text | vertical-text | alias | copy | move | no-drop | not-allowed | e-resize | n-resize | ne-resize | nw-resize | s-resize | se-resize | sw-resize | w-resize | ew-resize | ns-resize | nesw-resize | nwse-resize | col-resize | row-resize | all-scroll | zoom-in | zoom-out | grab | grabbing ] ]`

MDN has even discussed [removing formal syntax](https://github.com/mdn/data/issues/367#issuecomment-495163820) from their pages because visitors rarely uses them.

> We don't currently have a plan for what we want to do about formal syntax; we've even discussed removing it from our pages, as so few people actually use it. But this is a decision we'll have return to when we have more time,

I feel bad having to be this negative but I really would like to hear what you have to say about this.

**Comment by nojvek** [comment]
From the thread you linked I see this, so it seems it was just a discussion.

> We won't remove them lightly, don't worry. I appreciate the feedback.

I find `Syntax` super valuable, because `cursor: string` tells me very little. E.g for using cursor property I found this a gold mine. i.e `cursor: 'hand'` isn't valid, I need `cursor: 'pointer'`. Ha! Thanks to this I didn't even realize I could have cursor from a url. Today I learned (TIL)! 

I've been using a private build with formal syntax shown in code completion context, and I'm learning a ton. I've been doing css for a decade but I didn't quite understand the full breadth of values that could go in the property values. The formal syntax is a god send to be honest. I have to thank Mozilla for making this so nicely organized.

The strings are long, but they aren't impossibly long. MDN caps them to show top definition only, not all the recursive types. For that you have to read the mdn link. That is nice.

Personally `Syntax` is more valuable than `initial-value` or the css compatibility table. Although the compatibility table didn't make sense to me, what is `-x-` ? Took me a while to get it "ah it means browser specific prefix".

I like css-type backed by mdn data so much that (P)React experience feels subpar. I want to see the documentation for attributes and events right in code completion panel.

Please please please approve+merge this.
