### ISSUE TITLE
EOL characters and build artifacts

### ISSUE THREAD

**Issue by rtsao** [frenic/csstype#9]
Because `output.ts` is implemented using `os.EOL`, building the libdefs on a different operating system than Windows produces an enormous diff in the build artifacts.

This raises a few questions:

1. Should `index.d.ts` (and Flow equivalent) be checked into git?
2. If so, should a particular line ending be chosen?

**Comment by frenic** [comment]
I think the TypeScript and Flow definitions should be checked into Git. It's quite often you just want to have a look. I know it could result in annoying merge conflicts. But in those cases you just need to run `yarn build` to resolve it.

Fixed so that they use LF in e70d8a340ae0c5ac7410fb3ca8517b6d51eb6f90
